### ISSUE TITLE
Tx confirmed on the BitcoinZ blockchain, but not reflected in the wallet

### ISSUE THREAD

**Issue by vzykov** [bitcoinz-wallets/bitcoinz-copay-wallet#10]
(This same issue occurs both with [the 10.0.1 version of the wallet](https://github.com/anthony19114/MyBitcoinZ), and after upgrading to 10.0.3).

Here is my receive address, generated by the MyBitcoinZ wallet:

![screen shot 2017-12-31 at 9 15 16 pm](https://user-images.githubusercontent.com/13460199/34465168-08e0cb94-ee70-11e7-8504-f3021e617718.png)

Here's that address in BitcoinZ Explorer, with two confirmed incoming transactions: https://explorer.bitcoinz.site/address/t1TfkD4ynbX51NyCbYbM3nFvtrThajo8LHv

And here's the home screen of the MyBitcoinZ wallet: 

![screen shot 2017-12-31 at 9 22 27 pm](https://user-images.githubusercontent.com/13460199/34465193-c52ab81e-ee70-11e7-8d12-6c347e44e7cc.png)

And the transaction history inside "Personal Wallet"... not reflecting the above transactions:

![screen shot 2017-12-31 at 9 17 09 pm](https://user-images.githubusercontent.com/13460199/34465169-0c5b6856-ee70-11e7-96c1-b9fd974b6015.png)

**Comment by egyptianbman** [comment]
Hey @vzykov does anything happen when you over drag that screen down? -- as though you're trying to scroll above the top of the screen.

**Comment by vzykov** [comment]
Hey, thanks for the quick reply -- no areas of that screen seem to respond in any way to the pull-to-refresh gesture. 

When I click on the big label with "3.303416 BTCZ" though, it seems to be querying/refreshing something for a second: a little spin indicator appears and then disappears in the bottom right corner of the dark blue area, and then the "0.00 BTC" label blinks.

**Comment by vzykov** [comment]
I was able to get the wallet to update and show the new transactions and the resulting balance after going to Settings > Personal Wallet > More Options > Wallet Addresses > Scan addresses for funds.

**Comment by egyptianbman** [comment]
Excellent. I restarted the explorer this morning so that might've also resolved the issue. It looks like it was failing on random requests. Let us know if you experience any more issues; thanks!
