### ISSUE TITLE
QR Read

### ISSUE THREAD

**Issue by Lumiboy** [bitcoinz-wallets/bitcoinz-copay-wallet#16]
Only reads QR with Walletadress as text.
Would like to have it like bitcoin apps.

`bitcoinz:<WALLETADRESS>?amount=<AMOUNT>&message=<MESSAGE>`
For example: `bitcoinz:t1NTxNXsy1QmvikAVQcxNKvKsecowxghJvt?amount=1000&message=Donation`

**Comment by Lumiboy** [comment]
Maybe we can get it from https://github.com/mycelium-com/wallet-android/blob/fb12ac9d9149b12ecc5a50694e6815b9d11adca4/libs/zxing-android/src/main/java/com/google/zxing/client/android/DecodeFormatManager.java

**Comment by renuzit** [comment]
This issue should be resolved in v10.0.6. It's currently pushed to the play store as a beta.
