### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by dolenhil** [bitcoinz-wallets/bitcoinz-copay-wallet#19]
![bitcoinz](https://user-images.githubusercontent.com/17047767/35330555-94bb01b2-010c-11e8-8aeb-4186ab6ccee2.jpg)

Clean install and a keep receiving this , any ideas on how to fix it ?

**Comment by renuzit** [comment]
I believe you're looking for this project here:
https://github.com/bitcoinz-pod/bitcoinz-wallet
