### ISSUE TITLE
Sweep function failing on v10.0.4

### ISSUE THREAD

**Issue by NickRHill** [bitcoinz-wallets/bitcoinz-copay-wallet#20]
Launch wallet. "Scan private key". "Select Sweep paper wallet". 
You see 
Funds Found: ...

Expected:
Funds Found: 5BTCz

Click sweep anyway, Reports "cannot build transaction"

The sending functionality works OK. 

Verified by three people with different wallets. 
![screenshot_2018-01-25-17-06-58](https://user-images.githubusercontent.com/33939323/35401831-892f72a6-01f2-11e8-8e28-a6ee6b88a692.png)

**Comment by renuzit** [comment]
What application were you using to create the private keys? https://paper.btcz.rocks/ ??

**Comment by renuzit** [comment]
@NickRHill v10.0.5 has been uploaded to the Play store. Let me know if this resolves your issues!

**Comment by NickRHill** [comment]
Beta version fixes issue and I understand will be pushed to mainline soon, so closing. Thanks.
