### ISSUE TITLE
Android wallet not reading data from media URL

### ISSUE THREAD

**Issue by NickRHill** [bitcoinz-wallets/bitcoinz-copay-wallet#21]
The wallet registers media type bitcoinz: with the system. A URL formed in a web page thus will launch the wallet:
<a href="bitcoinz:t1Q9HcFH36GeybNyRCQogwb4Qrt95po1Bvc">address link text</a> 
<a href="bitcoinz:KwKC1GtHQ4PiX7k2UWRrgvBvFDsmgTE5W8ksyZSUSEvwwqAjfasP">private key link text</a> 

That is great. However, the wallet is not reading or using the URL data. It won't recognise the address or private key content. 

The use of private keys in this context may not be immediately obvious, but I can think of an important use case for marketing. And if the address import is fixed, the private key version may as well be implemented. This can take the user to the sweep wallet function.

**Comment by NickRHill** [comment]
Fixed in Beta version. Due to be rolled out.
Thanks 
Closing.

**Comment by renuzit** [comment]
Wait, this was fixed?

**Comment by NickRHill** [comment]
Sorry, wrong issue closed.

**Comment by renuzit** [comment]
This issue should be resolved in v10.0.6. It's currently pushed to the play store as a beta.

**Comment by NickRHill** [comment]
10.0.7 Android
If an address is delivered in a bitcoinz: URL, it functions well.
If a private key is delivered, in normal WIF format, it won't recognise that and go so sweep function.

**Comment by NickRHill** [comment]
It is possible to consider the bug report to have both a bug report, and a feature upgrade. Should I open a new bug report with the sweep private key from bitcoinz;  URL?

**Comment by renuzit** [comment]
So, I think the scope of this issue has been resolved, Private key being delivered in normal WIF format is probably a separate issue. I could create another issue and put any details you may have in it, like examples, etc.
