### ISSUE TITLE
Receive QR code gives incompatible URL format

### ISSUE THREAD

**Issue by NickRHill** [bitcoinz-wallets/bitcoinz-copay-wallet#26]
Beta version 10.0.6
Tested on Android 4.4.4 and 5.1
Click receive in app. App will display QR code. 

Scan QR code with same app on a different phone. Wallet shows QR code with URL format 
bitcoin:<address>
And an option to copy to clipboard.
Expected: Bring up payment amount.

It appears this bug is caused by the QR code URL format. The URL is encoding the URL format
bitcoin:<address>

I have generated a QR code with bitcoinz:<address> manually, and the app accepts this. 

Proposed fix: Make app encode the URL as bitcoinz: not bitcoin:

**Comment by renuzit** [comment]
This should be fixed in Version 10.0.7.

**Comment by NickRHill** [comment]
Confirmed 
Thanks.
