### ISSUE TITLE
Static Wallet Addresses

### ISSUE THREAD

**Issue by egyptianbman** [bitcoinz-wallets/bitcoinz-copay-wallet#33]
Our use case is we're using a multi signature wallet for community funds. The funds site keeps track of an address we generated and we'll be moving funds into that address as we shield from the donation address.

Currently, making a payment causes a new address to get created and the remainder to be deposited into that. This isn't ideal for our scenario. Ideally, when payments are made, send the remainder back to the source address, instead of creating a new one.

**Comment by renuzit** [comment]
<img width="524" alt="bitcoinz_wallet_and_facebook" src="https://user-images.githubusercontent.com/33474968/36846042-b154eb3e-1d1e-11e8-86c2-ba1281f6d3a6.png">

So there is this!

**Comment by egyptianbman** [comment]
Wow, awesome! <3
